version: '2'

services:
  spark:
    image: spark-air:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8090:8080'
    volumes:
      - ./lib:/opt/bitnami/spark/spark-lib
  spark-worker:
    image: spark-air:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - GOOGLE_APPLICATION_CREDENTIALS=${SPARK_HOME}/.google/credentials
    env_file:
      - ./../.env
    volumes:
      - ../.google/credentials:/opt/bitnami/spark/.google/credentials:ro
      - ./lib:/opt/bitnami/spark/spark-lib